### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kang-jisu** [kang-jisu/jstagram#1]
## 해보면 좋을 것들
- [ ] redis . nosql 알아보기
- [x] 회원 프로필 페이지
- [x] 구독,팔로우,친구 같은 기능 추가 
- [ ] 팔로우했을때, 안했을때 view 나누고 중복 팔로우 제거 , 팔로우 취소기능
- [ ] 게시글 좋아요
- [ ] 해시태그 또는 글 내용 , 유저 검색기능
## full stack
 - [ ] api 구현하기
 - [ ] react로 front page 만든거도 수정해서 연결해보기
## 핵데이
 - [ ] 자소서 쓰기
 - [ ] 소개 페이지 or 문서 만들기
